### ISSUE TITLE
Breadcrumb disappeared in deployed Demo App on Refresh

### ISSUE THREAD

**Issue by ani006** [udayvunnam/xng-breadcrumb#1]
On refresh breadcrumb gets disappeared!!

**Comment by udayvunnam** [comment]
Can you please elaborate. Does it get disappered or not shown with dynamic updated values

**Comment by ani006** [comment]
> Can you please elaborate. Does it get disappered or not shown with dynamic updated values

First time it's load fine but but as soon as hit refresh it gets disappeared!! For every routes not only dynamic updated values

**Comment by udayvunnam** [comment]
If you play around https://xng-breadcrumb.netlify.com, it shows breadcrumb even on page refresh. Can you provide a stackblitz to see the issue.

**Comment by ani006** [comment]
> If you play around https://xng-breadcrumb.netlify.com, it shows breadcrumb even on page refresh. Can you provide a stackblitz to see the issue.

if i do refresh with this url https://xng-breadcrumb.netlify.com it is giving me error.  
"Looks like you've followed a broken link or entered a URL that doesn't exist on this site."

**Comment by udayvunnam** [comment]
Okay I got that! the problem is with netlify redirects (deployed env), but not the library behaviour itself. Thanks for reporting. I will fix the deployment.

**Comment by udayvunnam** [comment]
@ani006 Irrespective of this, the library should work with your project even with refresh. Please let me know otherwise.

**Comment by udayvunnam** [comment]
@ani006 I have fixed the issue in deployment https://xng-breadcrumb.netlify.com. You should see that working on page refresh as well. cheers!

Please close the issue if this works:)

**Comment by ani006** [comment]
One 

> @ani006 I have fixed the issue in deployment https://xng-breadcrumb.netlify.com. You should see that working on page refresh as well. cheers!
> 
> Please close the issue if this works:)

One more thing i observed in my project that if i don't add breadcrumb for any particular router than also it showing the URL as breadcrumb. Can you tell why ?

**Comment by udayvunnam** [comment]
> One
> 
> > @ani006 I have fixed the issue in deployment https://xng-breadcrumb.netlify.com. You should see that working on page refresh as well. cheers!
> > Please close the issue if this works:)
> 
> One more thing i observed in my project that if i don't add breadcrumb for any particular router then also it showing the URL as breadcrumb. Can you tell why ?

As per the current design, breadcrumbs(same as route) will be shown even if there is no breadcrumbs defined
Please go through [README](https://github.com/udayvunnam/xng-breadcrumb/blob/master/README.md)
You have to explicitly define not to show breadcrumbs, by any of the below ways - `    {
      path: 'edit',
      component: MenteeEditComponent,
      data: { breadcrumbAlias: 'menteeEdit' }
    }
//-----------------------ALTERNATIVE------------------------
// use BreadcrumbService skip() or skipForAlias() methods
constructor(private breadcrumbService: BreadcrumbService) {}
this.breadcrumbService.skipForAlias('aliasName');

//-----------------------ALTERNATIVE------------------------

constructor(private breadcrumbService: BreadcrumbService) {}
this.breadcrumbService.skip('path/:param/toBeSkippedBreadcrumbRoute');
`

check this url - https://xng-breadcrumb.netlify.com/mentee/7/edit

I understand, this is not the desired behaviour always. I will make this behaviour optional with next minor release

**Comment by ani006** [comment]
> @ani006 Irrespective of this, the library should work with your project even with refresh. Please let me know otherwise.

Brother it's still doesn't work on refresh what could be the problem in my project ??
Please help me out

**Comment by udayvunnam** [comment]
> > @ani006 Irrespective of this, the library should work with your project even with refresh. Please let me know otherwise.
> 
> Brother it's still doesn't work on refresh what could be the problem in my project ??
> Please help me out

Here is a minimal stackblitz example that works on refresh as well - https://stackblitz.com/edit/xng-breadcrumb. 
Please create an example with your code or show me the code if it's open source

**Comment by udayvunnam** [comment]
@ani006 You can now disable the default behavior of showing breadcrumbs

**Disabling default mapping of route to breadcrumb label:
To avoid breadcrumb labels showing by default even for routes that don't have breadcrumb configuration set defaultMapping=false.

<xng-breadcrumb separator=">"></xng-breadcrumb>
released with version 1.2.0

**Comment by ani006** [comment]
Alright brother !! 
It's working fine now.. 
Thanks ....

**Comment by udayvunnam** [comment]
Discussion resolved in https://github.com/udayvunnam/xng-breadcrumb/issues/18
